version: "3.1"

services:
  nodeapi:
    image: mysql:5.7
    container_name: nodeapi
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nodeapi
      - MYSQL_PASSWORD=nodeapi
      - MYSQL_DATABASE=nodeapi
      - MYSQL_USER=nodeapi
      - TZ=America/Sao_Paulo
    restart: always
    command: --default-authentication-plugin=mysql_native_password
